# Generated by Django 5.0.6 on 2024-07-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HikingTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trail_name', models.CharField(max_length=100)),
                ('distance', models.CharField(max_length=100)),
                ('elevation_gain', models.CharField(max_length=100)),
                ('elevation_loss', models.CharField(max_length=100)),
                ('technical_difficulty', models.CharField(max_length=50)),
                ('max_elevation', models.CharField(max_length=100)),
                ('min_elevation', models.CharField(max_length=100)),
                ('trail_type', models.CharField(max_length=50)),
                ('total_time', models.CharField(max_length=100)),
                ('recorded', models.CharField(max_length=50)),
                ('url', models.URLField()),
            ],
        ),
    ]
