# Generated by Django 5.0.6 on 2024-07-06 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hikingtrail',
            name='kml_file_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
